name: Publish Package to npmjs
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - run: yarn install

      - name: Update version
        run: |
          version=$(jq -r .version package.json).$(git rev-parse --short HEAD)
          echo "$(jq --arg v "${version}" '.version = $v' package.json)" > package.json
      - run: yarn build

      - run: npm publish --tag $(git rev-parse --short HEAD)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
